version: "2.1"
services:
  openssh-server:
    image: ghcr.io/linuxserver/openssh-server
    container_name: openssh-server
    # hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      # - PUBLIC_KEY=yourpublickey #optional
      # - PUBLIC_KEY_FILE=/path/to/file #optional
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=pass #optional
      # - USER_PASSWORD_FILE=/path/to/file #optional
      - USER_NAME=user #optional
    volumes:
      - ./conifg:/config
    ports:
      - 2222:2222
    restart: unless-stopped